SELECT AA.CENTER_CD,
AA.CAR_GBN_CD,
AA.CAR_MNG_NO,
AA.RSVP_NO,
AA.CAR_NO,
AA.INOUT_TYPE_CD,
AA.IN_DTM,
AA.OUT_DTM
FROM (
    SELECT CENTER_CD,
           CAR_GBN_CD,
           CAR_MNG_NO,
           RSVP_NO,
           CAR_NO,
           INOUT_TYPE_CD,
           CASE WHEN INOUT_TYPE_CD = '01' THEN INOUT_DT
                ELSE NULL END AS IN_DTM,
           CASE WHEN INOUT_TYPE_CD = '01' AND LEAD(INOUT_TYPE_CD) OVER(PARTITION BY CENTER_CD, CAR_NO ORDER BY INOUT_DT) = '02'
                THEN LEAD(INOUT_DT) OVER(PARTITION BY CENTER_CD, CAR_NO ORDER BY INOUT_DT) 
                WHEN LAG(INOUT_TYPE_CD) OVER(PARTITION BY CENTER_CD, CAR_NO ORDER BY INOUT_DT) != '01' AND INOUT_TYPE_CD = '02'
                THEN INOUT_DT
                WHEN LAG(INOUT_TYPE_CD) OVER(PARTITION BY CENTER_CD, CAR_NO ORDER BY INOUT_DT) IS NULL AND INOUT_TYPE_CD = '02'
                THEN INOUT_DT
                ELSE NULL END AS OUT_DTM
    FROM TB_INOUT_TM_CAR
    WHERE 1 = 1
        AND CENTER_CD = 'DT1000'
        AND INOUT_DT BETWEEN TO_DATE('20181001' || '000000', 'YYYYMMDDHH24MISS') 
                        AND TO_DATE('20181008' || '235959', 'YYYYMMDDHH24MISS')
       ) AA
WHERE AA.IN_DTM IS NOT NULL
   OR AA.OUT_DTM IS NOT NULL
ORDER BY AA.CAR_NO;