--:1 = 'IFD'
-- TABLE CRUD
SELECT 'GRANT ' 
       || (CASE WHEN B.LV = 1 THEN 'INSERT' 
                WHEN B.LV = 2 THEN 'UPDATE' 
                WHEN B.LV = 3 THEN 'DELETE' 
                WHEN B.LV = 4 THEN 'SELECT' END)
       || ' ON ' || A.OWNER || '.' || A.TABLE_NAME || ' TO RL_' || :1 
       || (CASE WHEN B.LV = 1 THEN 'ADM_C' 
                WHEN B.LV = 2 THEN 'ADM_U' 
                WHEN B.LV = 3 THEN 'ADM_D' 
                WHEN B.LV = 4 THEN 'ADM_R' END)
       || ';' AS SCRIPT
  FROM (SELECT OWNER, TABLE_NAME
        FROM DBA_TABLES
        WHERE OWNER = :1 || 'ADM'
              AND TABLE_NAME NOT LIKE 'TMP%') A,
       (SELECT LEVEL AS LV
        FROM dual
        CONNECT  BY LEVEL <= 4) B 
UNION ALL
-- SEQUENCE SELECT
SELECT 'GRANT SELECT ON '|| A.OWNER ||'.'||A.OBJECT_NAME 
     ||' TO RL_' || :1 ||'ADM_SEQ;' AS SCRIPT
FROM DBA_OBJECTS A
WHERE OWNER= :1 || 'ADM'
AND OBJECT_TYPE = 'SEQUENCE'
UNION ALL
-- EXECUTE
SELECT 'GRANT EXECUTE ON ' || A.OWNER || '.' || A.OBJECT_NAME || ' TO RL_' || :1 ||
       (CASE WHEN OBJECT_TYPE IN ('PROCEDURE', 'PACKAGE') THEN 'ADM_PROC;'
             WHEN OBJECT_TYPE = 'FUNCTION' THEN 'ADM_FN;' END) AS SCRIPT
  FROM DBA_OBJECTS A
 WHERE OWNER = :1 || 'ADM'
   AND OBJECT_TYPE IN ('FUNCTION', 'PROCEDURE', 'PACKAGE')
UNION ALL
-- DEBUG
SELECT 'GRANT DEBUG ON ' || A.OWNER || '.' || A.OBJECT_NAME 
    || ' TO RL_' || :1 || 'ADM_DEBUG;' AS SCRIPT
  FROM(
        SELECT OWNER, OBJECT_NAME, OBJECT_TYPE
          FROM DBA_OBJECTS
         WHERE OWNER = :1 || 'ADM'
           AND OBJECT_TYPE IN ('FUNCTION', 'PROCEDURE', 'PACKAGE')
       ) A
UNION ALL
--5.2 시노님 부여
SELECT 'CREATE OR REPLACE SYNONYM '|| :1 
    || 'APP.'||OBJECT_NAME||' FOR '||OWNER||'.'||OBJECT_NAME
    ||';' AS SCRIPT
FROM DBA_OBJECTS
WHERE OWNER= :1 || 'ADM'
  AND OBJECT_TYPE IN ('VIEW','SEQUENCE','FUNCTION',
                      'PACKAGE','PROCEDURE','TABLE');
