SELECT USERID 
FROM SYSTEM.SQLPLUS_PRODUCT_PROFILE;

SELECT USER_ID , USERNAME 
FROM DBA_USERS;

SELECT DIRECTORY_NAME , DIRECTORY_PATH 
FROM DBA_DIRECTORIES;

CREATE directory TEMP_ADM AS '/oraarch/mig_dmp';
GRANT ALL ON directory TEMP_ADM TO system;

SELECT 'alter system disconnect session '''||sid||','||serial#||''' immediate;'
FROM v$session
WHERE username = 'JWMSAPP'

SELECT CASE WHEN OBJECT_TYPE = 'TABLE' THEN 'DROP '||OBJECT_TYPE||' "'|| OWNER || '"."' || OBJECT_NAME || '" CASCADE CONSTRAINTS;'
            WHEN OBJECT_TYPE = 'JOB' THEN 'BEGIN DBMS_SCHEDULER.DROP_JOB(JOB_NAME => '''||OWNER||'.'||OBJECT_NAME||'''); END;'
            WHEN OBJECT_TYPE = 'SCHEDULE' THEN 'BEGIN DBMS_SCHEDULER.DROP_SCHEDULE(SCHEDULE_NAME => '''||OWNER||'.'||OBJECT_NAME||'''); END;'
            ELSE 'DROP '||OBJECT_TYPE||' "'|| OWNER || '"."' || OBJECT_NAME || '";'
       END
FROM DBA_OBJECTS
WHERE OBJECT_TYPE NOT IN ('LOB','INDEX','PACKAGE BODY')
AND OWNER IN (SELECT userid FROM SYSTEM.SQLPLUS_PRODUCT_PROFILE)
--REGEXP_LIKE(OWNER,'^JDA|^I2TM|^IF');
--AND REGEXP_LIKE(OBJECT_TYPE, 'SEQUENCE|FUNCTION|PROCEDURE|PACKAGE|SYNONYM|VIEW|TABLE|TYPE') ;

