SELECT owner, OBJECT_NAME Table_Name,
TIMESTAMP LAST_DDL, CREATED, GENERATED
FROM all_objects
WHERE OWNER = 'DMSADM'
ORDER BY 3 DESC;

SELECT TABLE_NAME,
 PARTITION_NAME,
 SUBPARTITION_NAME,
 INSERTS,
 UPDATES,
 DELETES,
 TRUNCATED,
 TIMESTAMP
FROM ALL_TAB_MODIFICATIONS
WHERE table_owner = 'DMSADM'
ORDER BY TIMESTAMP DESC;