SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHAR_USED,
       CASE WHEN DATA_TYPE = 'VARCHAR2' AND CHAR_USED = 'C' 
            THEN DATA_LENGTH/4
            ELSE DATA_LENGTH
       END AS DATA_LENGTH
FROM DBA_TAB_COLS
WHERE OWNER = 'MORG'
AND DATA_LENGTH => 1024;


BEGIN 
	DBMS_STATS.GATHER_SCHEMA_STATS('MORG');
END ;

SELECT TABLE_NAME, NUM_ROWS
FROM DBA_TABLES
WHERE OWNER = 'MORG';


SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM DBA_CONS_COLUMNS
WHERE OWNER = 'MORG';

SELECT DC.TABLE_NAME, 
       DCC.COLUMN_NAME, 
       DC.CONSTRAINT_NAME, 
       DC.CONSTRAINT_TYPE, 
       DC.INDEX_NAME
FROM DBA_CONSTRAINTS DC 
     LEFT OUTER JOIN DBA_CONS_COLUMNS DCC
     ON DC.CONSTRAINT_NAME = DCC.CONSTRAINT_NAME
WHERE DC.OWNER = 'MORG';


SELECT CASE WHEN DC.CONSTRAINT_TYPE = 'P' THEN
            'ALTER TABLE '||DC.OWNER||'.'||DC.TABLE_NAME|| 
            ' RENAME CONSTRAINT '||DC.CONSTRAINT_NAME||' TO PK_'
            ||SUBSTR(DC.TABLE_NAME,INSTR2(DC.TABLE_NAME,'_',-1,2)+1,LENGTH(DC.TABLE_NAME))
            ||'_'||DCC.COLUMN_NAME||';'
            WHEN DC.CONSTRAINT_TYPE = 'C' THEN 
            'ALTER TABLE '||DC.OWNER||'.'||DC.TABLE_NAME|| 
            ' RENAME CONSTRAINT '||DC.CONSTRAINT_NAME||' TO CK_'
            ||SUBSTR(DC.TABLE_NAME,INSTR2(DC.TABLE_NAME,'_',-1,2)+1,LENGTH(DC.TABLE_NAME))
            ||'_'||DCC.COLUMN_NAME||';'       END AS RENAME_CONST,
       CASE WHEN DC.INDEX_NAME IS NOT NULL THEN
            'ALTER INDEX '||DC.OWNER||'.'||DC.INDEX_NAME|| 
            ' RENAME TO IDX_'||DC.TABLE_NAME||'_PK ;'
            ELSE NULL 
       END AS RENAME_IND
FROM DBA_CONSTRAINTS DC 
     LEFT OUTER JOIN DBA_CONS_COLUMNS DCC
     ON DC.CONSTRAINT_NAME = DCC.CONSTRAINT_NAME
WHERE DC.OWNER = 'MORG'
--AND DC.TABLE_NAME = 'TBCT_INSR_PLOAD_INSR'
AND (DC.CONSTRAINT_NAME LIKE 'SYS%' 
     OR DC.INDEX_NAME LIKE 'SYS%');

