SELECT TIMESTAMP_TO_SCN(TO_TIMESTAMP('2018-07-27 16:00:00', 'YYYY-MM-DD HH24:MI:SS')) FROM dual;

SELECT SYSDATE FROM dual;
SELECT TIMESTAMP_TO_SCN(SYSDATE) FROM dual;


SELECT "FILE#", "CHECKPOINT_CHANGE#" AS SCN, 
       SCN_TO_TIMESTAMP("CHECKPOINT_CHANGE#") AS SCN_TO_TIME,
       SYSDATE, TIMESTAMP_TO_SCN(SYSDATE) AS SYSDATE_TO_SCN
FROM v$datafile
;

SELECT EAI_NO, SCN_TO_TIMESTAMP(ORA_ROWSCN)
FROM JDAFO.TB_SHPM_H
WHERE ORA_ROWSCN > TIMESTAMP_TO_SCN('2018-09-18 09:35:00');