SELECT (
        SELECT listagg(USERNAME,', ') WITHIN GROUP(ORDER BY DEFAULT_TABLESPACE)
        FROM DBA_USERS 
        WHERE NVL( SUBSTR( DEFAULT_TABLESPACE, 1, 
                    INSTR( DEFAULT_TABLESPACE, '_',- 1 )), 0 )
                 = SUBSTR(UTS.TABLESPACE, 1, 
                   INSTR(UTS.TABLESPACE, '_',- 1 ))
       ) AS USERNAME,
       UTS.TABLESPACE, 
       SUM(UTS."SIZE") AS "SIZE(MB)",
       SUM(UTS.USED) AS "USED(MB)",
       SUM(UTS."FREE") AS "FREE(MB)",
       SUM(UTS.USED)/SUM(UTS."SIZE")*100 AS "USED_PERCENT"
FROM
  (
  SELECT
    DDF.FILE_NAME AS "FILE NAME",
    DDF.TABLESPACE_NAME AS TABLESPACE,
    NVL(DDF.BYTES/1024/1024, 0) AS "SIZE",
    NVL((DDF.BYTES - NVL(S.BYTES, 0))/ 1024 / 1024, 0) AS USED,
    NVL(S.BYTES/1024/1024, 0) AS "FREE"
  FROM
    SYS.DBA_DATA_FILES DDF 
    LEFT OUTER JOIN
    (
        SELECT FILE_ID, SUM(BYTES) AS BYTES
        FROM SYS.DBA_FREE_SPACE
        GROUP BY FILE_ID
    ) S
    ON DDF.FILE_ID = S.FILE_ID
--  WHERE TABLESPACE_NAME NOT IN ('SYSTEM','SYSAUX','USERS','UNDOTBS1')
  ) UTS
GROUP BY UTS.TABLESPACE
ORDER BY 1;


SELECT USERNAME, DEFAULT_TABLESPACE
FROM DBA_USERS
;



SELECT TABLESPACE_NAME, SUM(BYTES)
FROM DBA_FREE_SPACE
GROUP BY TABLESPACE_NAME;


SELECT NVL((SELECT listagg(DO.OWNER,', ') WITHIN GROUP(ORDER BY DO.TABLESPACE_NAME)
            FROM (SELECT OWNER, TABLESPACE_NAME
                  FROM DBA_TABLES
                  GROUP BY OWNER, TABLESPACE_NAME
                  UNION 
                  SELECT OWNER, TABLESPACE_NAME
                  FROM DBA_INDEXES
                  GROUP BY OWNER, TABLESPACE_NAME) DO
                  WHERE DO.TABLESPACE_NAME = VT.TABLESPACE_NAME), 'UNKNOWN?') AS USERNAME,
        VT.TABLESPACE_NAME,
        VT.SIZE_MB,
        ROUND(VT.SIZE_MB-VT.FREE_MB) AS USED_MB,
        ROUND(VT.FREE_MB) AS FREE_MB,
        ROUND((1-(VT.FREE_MB/VT.SIZE_MB))*100,2) AS USED_PER
FROM
(SELECT DDF.TABLESPACE_NAME, SUM(DDF.BYTES)/1024/1024 AS SIZE_MB, 
 (SELECT SUM(DFS.BYTES)/1024/1024 
  FROM DBA_FREE_SPACE DFS 
  WHERE DDF.TABLESPACE_NAME = DFS.TABLESPACE_NAME)AS FREE_MB 
 FROM DBA_DATA_FILES DDF 
 WHERE DDF.TABLESPACE_NAME NOT IN ('SYSTEM','SYSAUX','USERS','UNDOTBS1')
 GROUP BY DDF.TABLESPACE_NAME) VT 
 ORDER BY TABLESPACE_NAME;
 
SELECT *
FROM (SELECT OWNER, TABLESPACE_NAME
  FROM DBA_TABLES
  GROUP BY OWNER, TABLESPACE_NAME
  UNION 
  SELECT OWNER, TABLESPACE_NAME
  FROM DBA_INDEXES
  GROUP BY OWNER, TABLESPACE_NAME)
WHERE TABLESPACE_NAME NOT IN ('SYSTEM','SYSAUX','USERS','UNDOTBS1')
;
