SELECT * FROM V$DATABASE;

SELECT * FROM NLS_DATABASE_PARAMETERS;

SELECT NAME, DISPLAY_VALUE FROM V$PARAMETER ;

SELECT NAME, VALUE FROM V$PARAMETER WHERE ISDEFAULT = 'FALSE';

SELECT USERNAME, PROFILE, PASSWORD_VERSIONS, ACCOUNT_STATUS, 
       DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE
FROM DBA_USERS
WHERE USERNAME NOT IN ('ANONYMOUS','APEX_030200','APEX_PUBLIC_USER','APPQOSSYS','BI',
'CTXSYS','DBSNMP','DIP','EXFSYS','FLOWS_FILES','HR','IX','MDDATA',
'MDSYS','MGMT_VIEW','OE','OLAPSYS','ORACLE_OCM','ORDDATA',
'ORDPLUGINS','ORDSYS','OUTLN','OWBSYS','OWBSYS_AUDIT','PM',
'SCOTT','SH','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR',
'SPATIAL_WFS_ADMIN_USR','SYS','SYSMAN','SYSTEM','WMSYS',
'XDB','XS$NULL','OJVMSYS','SYSKM','GSMCATUSER','SYSBACKUP',
'SYSDG','GSMUSER','AUDSYS','GSMADMIN_INTERNAL');

SELECT PROFILE, RESOURCE_NAME, LIMIT
FROM DBA_PROFILES
WHERE PROFILE IN ('DEFAULT','PRIV_USER');

SELECT ddf.TABLESPACE_NAME,  
       SUBSTR(ddf.FILE_NAME, 1, INSTR(ddf.FILE_NAME,'/',-1)) AS DIRECTORY,
       SUBSTR(ddf.FILE_NAME, INSTR(ddf.FILE_NAME,'/',-1)+1, LENGTH(ddf.FILE_NAME)) AS FILENAME,
       ddf.BYTES/(1024*1024) AS MBYTES
FROM v$datafile vdf, DBA_DATA_FILES ddf
WHERE vdf.FILE# = ddf.FILE_ID
UNION ALL
SELECT TABLESPACE_NAME,  
       SUBSTR(FILE_NAME, 1, INSTR(FILE_NAME,'/',-1)) AS DIRECTORY,
       SUBSTR(FILE_NAME, INSTR(FILE_NAME,'/',-1)+1, LENGTH(FILE_NAME)) AS FILENAME,
       BYTES/(1024*1024) AS MBYTES
FROM DBA_TEMP_FILES;

SELECT GROUP#, MEMBERS, BYTES/1024/1024 AS MB
FROM v$log;

SELECT OWNER, count(OBJECT_NAME)
FROM DBA_OBJECTS
WHERE OWNER NOT IN ('ANONYMOUS','APEX_030200','APEX_PUBLIC_USER','APPQOSSYS','BI',
'CTXSYS','DBSNMP','DIP','EXFSYS','FLOWS_FILES','HR','IX','MDDATA',
'MDSYS','MGMT_VIEW','OE','OLAPSYS','ORACLE_OCM','ORDDATA',
'ORDPLUGINS','ORDSYS','OUTLN','OWBSYS','OWBSYS_AUDIT','PM',
'SCOTT','SH','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR',
'SPATIAL_WFS_ADMIN_USR','SYS','SYSMAN','SYSTEM','WMSYS',
'XDB','XS$NULL','OJVMSYS','SYSKM','GSMCATUSER','SYSBACKUP',
'SYSDG','GSMUSER','AUDSYS','GSMADMIN_INTERNAL')
GROUP BY OWNER;

SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
FROM DBA_OBJECTS
WHERE STATUS <> 'VALID';

SELECT OWNER, JOB_NAME, PROGRAM_NAME, JOB_TYPE, JOB_ACTION, 
       SCHEDULE_OWNER, SCHEDULE_NAME, SCHEDULE_TYPE,
       JOB_CLASS, LAST_START_DATE, LAST_RUN_DURATION
FROM DBA_SCHEDULER_JOBS
WHERE ENABLED = 'TRUE';

SELECT JOB, LOG_USER, BROKEN, WHAT, NEXT_DATE, INTERVAL, LAST_SEC 
FROM DBA_JOBS;

SELECT GRANTEE, PRIVILEGE, ADMIN_OPTION
FROM DBA_SYS_PRIVS
WHERE GRANTEE IN ('TECHDBO','KXBWH','POLESTAR','IDC','EWS_USER',
'TECHDBA','EDIMIG','P_LKM8407','P_KJGUY','YSKIM50',
'P_YHCHO1','P_KIMSH22','P_KONGDAEHO','P_WHASSUPP8','RL_SELECT_KXBWH')
ORDER BY GRANTEE;

SELECT GRANTED_ROLE, GRANTEE, ADMIN_OPTION
FROM DBA_ROLE_PRIVS
WHERE GRANTEE IN ('TECHDBO','KXBWH','POLESTAR','IDC','EWS_USER',
'TECHDBA','EDIMIG','P_LKM8407','P_KJGUY','YSKIM50',
'P_YHCHO1','P_KIMSH22','P_KONGDAEHO','P_WHASSUPP8')
ORDER BY GRANTEE;

SELECT ROLE, OWNER, TABLE_NAME, PRIVILEGE
FROM ROLE_TAB_PRIVS
WHERE OWNER NOT IN ('ANONYMOUS','APEX_030200','APEX_PUBLIC_USER','APPQOSSYS','BI',
'CTXSYS','DBSNMP','DIP','EXFSYS','FLOWS_FILES','HR','IX','MDDATA',
'MDSYS','MGMT_VIEW','OE','OLAPSYS','ORACLE_OCM','ORDDATA',
'ORDPLUGINS','ORDSYS','OUTLN','OWBSYS','OWBSYS_AUDIT','PM',
'SCOTT','SH','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR',
'SPATIAL_WFS_ADMIN_USR','SYS','SYSMAN','SYSTEM','WMSYS',
'XDB','XS$NULL','OJVMSYS','SYSKM','GSMCATUSER','SYSBACKUP',
'SYSDG','GSMUSER','AUDSYS','GSMADMIN_INTERNAL')
ORDER BY ROLE, OWNER, TABLE_NAME;

SELECT *
FROM DBA_DB_LINKS;